# Generated by Django 2.2.7 on 2019-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191117_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
