# Generated by Django 2.2.7 on 2019-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_edit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=30)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='UserPhotos/%username/')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
