# Generated by Django 2.2.7 on 2019-11-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_siteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
