# Generated by Django 2.2.7 on 2020-03-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
