# Generated by Django 2.2.7 on 2020-03-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
