# Generated by Django 2.2.7 on 2020-04-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20200406_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('V1', models.FloatField()),
                ('V2', models.FloatField()),
                ('RZAB1', models.FloatField()),
                ('RZAB2', models.FloatField()),
                ('RPL', models.FloatField()),
                ('DEP1', models.FloatField()),
                ('DEP2', models.FloatField()),
                ('RASH1', models.FloatField()),
                ('RASH2', models.FloatField()),
                ('B', models.FloatField()),
                ('A', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
