# Generated by Django 2.2.7 on 2020-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='A',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='B',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='DEP1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='DEP2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='RASH1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='RASH2',
            field=models.FloatField(null=True),
        ),
    ]
